# Generated by Django 5.0.4 on 2024-05-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='entry',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GeneratedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generated_photos/')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
