# Generated by Django 5.0.4 on 2024-05-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_author_entry_user_entry_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='summary',
        ),
    ]
